/** Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
**/

#include <stdio.h>

int main() {
	int sum = 0;
	// Starting the Fibonacci sequence with 1, 2
	int first = 1;
	int second = 2;
	int next = first + second;

	// Consider all terms below four million
	while (next < 4000000) {
		// Check if the value is even
		if (next % 2 == 0) {
			// If so, add it to the accumulated sum
			sum = sum  + next;
		}
		// Generate the next term in the sequence
		first = second;
		second = next;
		next = first + second;
	}

	// Print out the sum, plus the second term because it's also even
	printf("%d", sum + 2);
}